# Generated by Django 5.1.3 on 2024-11-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('accounting_date', models.DateField()),
                ('transaction_date', models.DateField()),
                ('observation', models.CharField(max_length=1000)),
                ('expanded_code', models.CharField(max_length=1000)),
                ('movement_number', models.PositiveIntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
