# Generated by Django 5.1.3 on 2024-11-23 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_bankingcredentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('bank', models.CharField(blank=True, max_length=30, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bankingcredentials',
            name='created_at',
            field=models.DateTimeField(default='2024-01-05 00:00:00 -0300'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankingcredentials',
            name='updated_at',
            field=models.DateTimeField(default='2024-01-05 00:00:00 -0300'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankmovement',
            name='bank_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='apps.bankaccount'),
            preserve_default=False,
        ),
    ]
