# Generated by Django 5.1.3 on 2024-11-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bankingcredentials',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bankingcredentials',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bankmovement',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bankmovement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
