# Generated by Django 5.1.3 on 2024-11-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_userdetail_created_at_userdetail_updated_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bankmovement',
            constraint=models.UniqueConstraint(fields=('bank_account', 'movement_number'), name='unique_bank_account_movement_number'),
        ),
    ]
