# Generated by Django 5.1.3 on 2024-11-24 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_processedservicelisting'),
        ('apps', '0008_bankaccount_full_name'),
    ]

    operations = [
    ]
