version: "3.8"

services:
  nginx:
    image: nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./static:/static:delegated
      - ./nginx/stage.conf:/etc/nginx/conf.d/default.conf:delegated
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    build:
      dockerfile: Dockerfile
      context: .
    platform: linux/arm64
    image: template_app_compose
    hostname: django.backend-prod
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code:delegated
    environment:
      - DB_HOST=host.docker.internal
    ports:
      - "8000:8000"
      - "8889:8889" # ipython notebook
